### ISSUE TITLE
Kubernetes学习  Deployment

### ISSUE THREAD

**Issue by Vincent-Chou** [Vincent-Chou/blog#10]
>Deployment为Pod和Replica Set（升级版的 Replication Controller）提供声明式更新。

典型的用例如下：

- 使用Deployment来创建ReplicaSet。ReplicaSet在后台创建pod。检查启动状态，看它是成功还是失败。
- 然后，通过更新Deployment的PodTemplateSpec字段来声明Pod的新状态。这会创建一个新的ReplicaSet，Deployment会按照控制的速率将pod从旧的ReplicaSet移动到新的ReplicaSet中。
- 如果当前状态不稳定，回滚到之前的Deployment revision。每次回滚都会更新Deployment的revision。
- 扩容Deployment以满足更高的负载。
- 暂停Deployment来应用PodTemplateSpec的多个修复，然后恢复上线。
- 根据Deployment 的状态判断上线是否hang住了。
- 清除旧的不必要的 ReplicaSet。

## 创建 Deployment
```yaml
metadata:
  name: centos-deployment
  namespace: stb2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: centos-stb2-pod
    spec:
      containers:
      - name: centos
        imagePullPolicy: IfNotPresent
        image: centos-base
        ports:
        - containerPort: 8080
      nodeSelector:
        environment: stb2

```
```
kubectl create -f <dp-file> --record
```
将kubectl的 --record 的 flag 设置为 true可以在 annotation 中记录当前命令创建或者升级了该资源。这在未来会很有用，例如，查看在每个 Deployment revision 中执行了哪些命令。
