### ISSUE TITLE
Kubernetes学习 Volume [hostPath]

### ISSUE THREAD

**Issue by Vincent-Chou** [Vincent-Chou/blog#16]
## hostPath
　　``hostPath`` volume映射node文件系统中的文件或者目录到pod里。大多数Pod都不需要这个功能，但对于一些特定的场景，该特性还是很有作用的。这些场景包括： 
　　1.  运行的容器需要访问Docker内部结构：使用hostPath映射/var/lib/docker 
　　2.  在容器中运行cAdvisor，使用hostPath映射/dev/cgroups 
　　不过，使用这种volume要小心，因为： 
　　1.  配置相同的pod（如通过podTemplate创建），可能在不同的Node上表现不同，因为不同节点上映射的文件内容不同 
　　2.  当Kubernetes增加了资源敏感的调度程序，hostPath使用的资源不会被计算在内 
　　3.  宿主机下创建的目录只有root有写权限。你需要让你的程序运行在privileged container上，或者修改宿主机上的文件权限。 
　　pod示例：
```yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos-deployment
  namespace: stb2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: centos-stb2-pod
    spec:
      containers:
      - name: centos
        imagePullPolicy: IfNotPresent
        image: centos-base
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /workDir
          name: test-volume
      nodeSelector:
        environment: stb2
      volumes:
      - name: test-volume
        hostPath:
          path: /workspace/stb2/centos-test

```
