### ISSUE TITLE
配置管理工具-ansible (三)

### ISSUE THREAD

**Issue by Vincent-Chou** [Vincent-Chou/blog#43]
> 本章节主要介绍playbook相关

**什么是ad-hoc 命令?**
```
ad-hoc 命令是一种可以快速输入的命令，而且不需要保存起来的命令。就相当于bash中的一句话shell。
```

**什么是playbook**
```
Playbooks与Ad-Hoc相比，是一种完全不同的运用Ansible的方式，而且是非常之强大的；也是系统ansible命令的集合，其利用yaml语言编写，运行过程，ansbile-playbook命令根据自上而下的顺序依次执行。
简单来说，Playbooks 是一种简单的配置管理系统与多机器部署系统的基础。与现有的其他系统有不同之处，且非常适合于复杂应用的部署。
同时，Playbooks开创了很多特性，它可以允许你传输某个命令的状态到后面的指令，如你可以从一台机器的文件中抓取内容并附为变量，然后在另一台机器中使用，这使得你可以实现一些复杂的部署机制，这是ansible命令无法实现的。
Playbooks可用于声明配置，更强大的地方在于，在Playbooks中可以编排有序的执行过程，甚至于做到在多组机器间，来回有序的执行特别指定的步骤。并且可以同步或异步的发起任务。
我们使用Ad-Hoc时，主要是使用 /usr/bin/ansible 程序执行任务.而使用Playbooks时，更多是将之放入源码控制之中，用之推送你的配置或是用于确认你的远程系统的配置是否符合配置规范。
```
**那为什么还要用Ad-hoc**
```
一般来说，ansible强大之处在于playbook,而ad-hoc方式最大优势在于处理简单问题时，只需要临时一条命令就能执行。
```
**Playbook 语言的示例**
>playbooks 的格式是yaml，语法做到最小化，意在避免 playbooks 成为一种编程语言或是脚本，但它也并不是一个配置模型或过程的模型。
playbook是由一个或多个“play”组成的列表。play的主要功能在于将事先归并为一组的主机装扮成事先通过Ansible中的tasks定义好的角色（play的内容被称为tasks，即任务）。从根本上来讲所谓tasks无非是调用Ansible的一个module。将多个“play”组织在一个playbook中即可以让它们联同起来按事先编排的机制一同工作。
"plays"算是一个类比，可以通过多个plays告诉系统做不同的事情，不仅是定义一种特定的状态或模型。也可以在不同时间运行不同的plays。
对于初学者，这里有一个playbook，其中仅包含一个play：
```yaml
---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: write the apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=httpd state=started
  handlers:
    - name: restart apache
      service: name=httpd state=restarted

#第一行中，文件开头为　---；这是YAML将文件解释为正确的文档的要求。YAML允许多个“文档”存在于一个文件中，每个“文档”由 --- 符号分割，但Ansible只需要一个文件存在一个文档即可，因此这里需要存在于文件的开始行第一行。

#YAML对空格非常敏感，并使用空格来将不同的信息分组在一起，在整个文件中应该只使用空格而不使用制表符，并且必须使用一致的间距，才能正确读取文件。相同缩进级别的项目被视为同级元素。

#以 - 开头的项目被视为列表项目。作为散列或字典操作，它具有key：value格式的项。YAML文档基本上定义了一个分层的树结构，其中位于左侧是包含的元素。YAML文件扩展名通常为.yaml或者.yml。

```
**Playbook 构成**
```vim
Playbook主要有以下四部分构成：

target section：定义将要执行playbook的远程主机组
variable section：定义playbook运行时需要使用的变量
task section：定义将要在远程主机上执行的任务列表
handler section：定义task执行完成以后需要调用的任务
而Playbook对应的目录层有五个，分别如下：
一般所需的目录层有：(视情况可变化)

1. vars 变量层
2. tasks 任务层
3. handlers 触发条件
4. files 文件
5. template 模板
```

  - **Hosts（主机）与Users（用户）**
  我们可以为playbook中的每一个play，个别的选择操作的目标机器是哪些，以哪个用户身份去完成要执行的步骤（called tasks）
```yaml
---
- hosts: webservers
  remote_user: root
  tasks:
    - name: test connection
      remote_user: yourname
      sudo: yes
```
  playbook中的每一个play的目的都是为了让某个或某些主机以某个指定的用户身份执行任务。

  >hosts：用于指定要执行指定任务的主机其可以是一个或多个,由逗号为分隔符分隔主机组
remote_user：用于指定远程主机上的执行任务的用户。不过remote_user也可用于各tasks中。也可以通过指定其通过sudo的方式在远程主机上执行任务其可用于play全局或某任务。此外甚至可以在sudo时使用sudo_user指定sudo时切换的用户
user：与remote_user相同
sudo：如果设置为yes，执行该任务组的用户在执行任务的时候，获取root权限
sudo_user：如果设置user为bob，sudo为yes，sudo_user为tom时，则bob用户在执行任务时会获得tom用户的权限
connection：通过什么方式连接到远程主机，默认为ssh
gather_facts：除非明确说明不需要在远程主机上执行setup模块，否则默认自动执行。如果确实不需要setup模块传递过来的变量，则可以将该选项设置为False

  说明：
  * 参数remote_user以前写做user，在Ansible 1.4以后才改为remote_user。主要为了不跟user模块混淆（user模块用于在远程系统上创建用户）
  * 如果我们需要在使用sudo时指定密码，可在运行ansible-playbook命令时加上选项 --ask-sudo-pass (-K)。如果使用sudo时，playbook疑似被挂起，可能是在sudo prompt处被卡住，这时可执行 Control-C(正文结束字符)杀死卡住的任务，再重新运行一次。
  * 当使用sudo_user切换到非root用户时，模块的参数会暂时写入/tmp目录下的一个随机临时文件。当命令执行结束后。临时文件立即删除。这种情况发生在普通用户的切换时，比如从“bob”切换到“tom”，切换到root账户时，不会发生，如从“bob”切换到 “root”，直接以普通用户或root身份登录也不会发生。如果不希望这些数据在短暂的时间内可以被读取（不可写），请避免在sudo_user中传递未加密的密码。其它情况下，“/tmp” 目录不被使用，这种情况不会发生。Ansible 也有意识的在日志中不记录密码参数

  **tasks 列表和 action**
```
每一个play包含了一个tasks列表（任务列表）。

任务列表中的各任务按次序逐个在hosts中指定的所有主机上执行即在所有主机上完成第一个任务后再开始第二个。在自上而下运行某playbook时如果中途发生错误，所有已执行任务都将回滚，因此在更正playbook后重新执行即可。

每一个tasks必须有一个名称name，这样在运行playbook时，从其输出的任务执行信息中可以很好的辨别出是属于哪一个tasks的。如果没有定义name，“action”的值将会用作输出信息中标记特定的tasks。

tasks的目的是使用指定的参数执行模块，而在模块参数中可以使用变量。模块执行是幂等的，这意味着多次执行是安全的，因为其结果均一致。每个tassk都应该有其name用于playbook的执行结果输出，建议其内容尽可能清晰地描述任务执行步骤。如果未提供name则action的结果将用于输出。

如果要声明一个tasks，以前有一种格式:“action: module options”（可能在一些老的playbooks中还能见到）。现在推荐使用更常见的格式:“module: options”。

下面是一种基本的taska的定义，service moudle使用key=value格式的参数，这也是大多数module使用的参数格式：
```

```yaml
tasks:
 - name: make sure apache is running
   service: name=httpd state=running

# 在众多模块中，只有command和shell模块仅需要给定一个列表而无需使用“key=value”格式如下：
tasks:
 - name: disable selinux
   command: /sbin/setenforce 0

# 使用command module和shell module时，我们需要关心返回码信息，如果有一条命令，它的成功执行的返回码不是0，我们可以这样做：
tasks:
 - name: run this command and ignore the result
   shell: /usr/bin/somecommand || /bin/true
# 或者使用ignore_errors来忽略错误信息
tasks:
  - name: run this command and ignore the result
    shell: /usr/bin/somecommand
    ignore_errors: True

# 如果action行看起来太长，可以使用space（空格）或者indent（缩进）隔开连续的一行：
tasks:
  - name: Copy ansible inventory file to client
    copy: src=/etc/ansible/hosts dest=/etc/ansible/hosts
            owner=root group=root mode=0644
```

  **Handlers 在发生改变时执行的操作**
```
上面我们曾提到过，module具有“幂等”性，所以当远程主机被人改动时，可以重放playbooks达到恢复的目的。playbooks本身可以识别这种改动，并且有一个基本的event system（事件系统），可以响应这种改动。

（当发生改动时）“notify”这个actions会在playbook的每一个tasks结束时被触发，而且即使有多个不同的tasks通知改动的发生，“notify” actions只会被触发一次。这样可以避免多次有改变发生时每次都执行指定的操作，取而代之仅在所有的变化发生完成后一次性地执行指定操作。

在“notify”中列出的操作称为handlers，即“notify”中调用handlers中定义的操作。

说明：
在“notify”中定义内容一定要和tasks中定义的 - name 内容一样，这样才能达到触发的效果，否则会不生效。

举例来说，比如多个resources指出因为一个配置文件被改动，所以apache需要重新启动，但是重新启动的操作只会被执行一次。

这里有一个例子，当一个文件的内容被改动时，重启两个services：
```

```yaml
- name: template configuration file
  template: src=template.j2 dest=/etc/foo.conf
  notify:
     - restart memcached
     - restart apache
```

```
“notify”下列出的即是 handlers。
handlers也是一些tasks的列表，通过名字来引用，它们和一般的tasks并没有什么区别。handlers是由通知者进行notify，如果没有被notify，handlers不会执行。不管有多少个通知者进行了notify，等到play中的所有tasks执行完成之后，handlers也只会被执行一次。

这里是一个 handlers 的示例：
```

```yaml
handlers:
    - name: restart memcached
      service:  name=memcached state=restarted
    - name: restart apache
      service: name=apache state=restarted
```

```
Handlers最佳的应用场景是用来重启服务，或者触发系统重启操作。除此以外很少用到了。

说明：handlers会按照声明的顺序执行。
```
