### ISSUE TITLE
Kubernetes学习  POD/RC/SERVICE

### ISSUE THREAD

**Issue by Vincent-Chou** [Vincent-Chou/blog#5]
#Kubernetes学习  
***
接上篇kubernetes 安装完成
这一篇希望实现的效果是给NODE打上label，然后将应用根本label发布到指定的NODE上面
提前给node节点打上指定label
```
# kubectl label nodes <-nodename-> <label-key>=<label-value>
kubectl label nodes node01 environment=stb1
```

***
## `POD`
1. 创建pod文件---nginx-pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
   name: nginx-stb1
   labels:
     name: nginx-stb1
spec:
  containers:
  - name: nginx-stb1
    image: nginx:stable
    ports:
    - containerPort: 80

```
 1.1 创建pod
```
kubectl create -f nginx-pod.yaml
```
 1.2 查看pod创建在哪个node上
```
kubectl get pods
```
 1.3 到对应node，可以通过docke ps -a 查看container启动状态
 1.4 查看 pod 详细信息
```
kubectl describe pod <-podname->
```
``kubectl get pod <-podname->  -o yaml或者kubectl get pod <-podname-> -o json 获取pod更为详细的信息``
