### ISSUE TITLE
Kubernetes 学习 namespace

### ISSUE THREAD

**Issue by Vincent-Chou** [Vincent-Chou/blog#6]
>Namespace（命名空间）是kubernetes系统中的另一个重要的概念，通过将系统内部的对象“分配”到不同的Namespace中，形成逻辑上分组的不同项目、小组或用户组，便于不同的分组在共享使用整个集群的资源的同时还能被分别管理。
>Kubernetes集群在启动后，会创建一个名为“default”的Namespace，如果不特别指明Namespace，则用户创建的Pod、RC、Service都被系统创建到“default”的Namespace中。

- 查询
```
kubectl get namespace
```

- 创建
```yaml
apiVersion: v1
kind: Namespace
metadata:
    name: stb1
```

- 对POD/RC/SERVICE指定namespace
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
   name: nginx-stb1-controller
   labels:
     name: nginx-stb1-controller
   namespace: stb1
spec:
  replicas: 2
  selector:
     name: nginx-stb1-pod
  template:
    metadata:
     labels:
       name: nginx-stb1-pod
    spec:
      containers:
      - name: nginx-stb1
        image: nginx:stable
        ports:
        - containerPort: 80
      nodeSelector:
        environment: stb1
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-stb1-service
  labels:
    name: nginx-stb1-service
  namespace: stb1
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    nodePort: 30001
  selector:
    name: nginx-stb1-pod
```

>kubectl get pods/rc/service时，没有任何结果，因为默认的是查询namespace=default的，所以要加上namespace参数。同理创建RC/Service也是一样的。
通过使用Namespace来组织k8s的各种对象，可以实现对用户的分组，即“多租户”管理。对不同的租户还可以进行单独的资源配额设置和管理，使得整个集群的资源配置非常灵活、方便。关于租户配额稍后学习。
