### ISSUE TITLE
Kubernetes学习 LimitRange

### ISSUE THREAD

**Issue by Vincent-Chou** [Vincent-Chou/blog#7]
>LimitRange(简称limits)基于namespace的资源管理，包括pod和container的最小、最大和default、defaultrequests等。
一旦创建limits，以后创建资源时，K8S将该limits资源限制条件默认/强制给pod，创建后发现不符合规则，将暂停创建pod。
在创建资源时，用户可以为pod自定义资源管理限制，在创建时会去检查和匹配limits值，发现不匹配将在创建时报错。创建后，该pod的资源使用遵守自定义规则，而不会遵守namespace的limits限制。

- 创建
```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: stblimits
spec:
  limits:
  - max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: "1"
      memory: 2Gi
    type: Pod

  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "1.5"
      memory: 3Gi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: "1"
      memory: "2Gi"
    type: Container
```

### type： Container
```
min：资源紧张时，最低保证可以使用的资源是： CPU 1个核，内存2G 
max：资源空闲时，最大可以使用的资源是：CPU 2个核，内存4G
default：默认时，限制使用的资源是：CPU 2个核，内存4G
defaultRequest：默认时，最低保证可以使用的资源是： CPU 1.5个核，内存3G
```

### type： Container
```
min：最低保证可以使用的资源是： CPU 1个核，内存2G
max最大可以使用的资源是：CPU 2个核，内存4G
```

### 创建指定namespace的limitrange
```
kubectl create -f <limitrange-file> -n <namespace-name>

# 查看创建好的资源限制
kubectl get limits -n <namespace-name>
```

## 使用规则

1. 每个namespace应该只有一个limits；

2. limits值设置：
```
每容器（type： Container）
    max>=default>=defaultRequest>min
每pod（type： Pod）
    max>=min
整个
    容器的max*容器数<=pod的max
    容器的min*容器数<=pod的min
```
3. 创建资源时，pod自定义资源限制的规则：
```
自定义的单个request>=limits的容器的defaultrequets
自定义的request的总和>=limits的pod的min
自定义的单个limit<=limits的容器的requets
自定义的limit的总和<=limits的pod的max
```

### 为了防止出现创建资源失败的情况，个人建议：
- 只使用limits的pod或者container中的一种，尽量不使用同时使用，特别在pod中有多容器需求的情况下。
- 尽量使用max，尽量不同时使用max和min
- 由于limits会针对该namespace下的所有新建的pods，所以在该namespace下应该运行哪些资源需求相同的业务
- 在复杂的limits配置下，不要在创建资源时使用自定义配置。
